name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: '172054/adserver.services1:$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
     
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Create Storage Account'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Training-rg-sc'
        subscriptionId: '44e26024-4977-4419-8d23-0e1e22e8804e'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Training-rg'
        location: 'Central India'
        templateLocation: 'Linked artifact'
        csmFile: 'ARMTemplate/template.json'
        csmParametersFile: 'ARMTemplate/parameter.json'
        deploymentMode: 'Incremental'